Striide\GeoBundle\Entity\Countries:
  type: entity
  table: striide_geo_countries
  repositoryClass: Striide\GeoBundle\Entity\CountriesRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 255
      fixed: false
      nullable: false
  lifecycleCallbacks: {  }
